#!/usr/bin/env python3
import argparse
import base64
import subprocess
import tempfile
import textwrap
from pathlib import Path


def _run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def _compile_metallib(input_metal: Path, sdk: str, tmpdir: Path) -> bytes:
    base = input_metal.stem
    air = tmpdir / f"{base}_{sdk}.air"
    lib = tmpdir / f"{base}_{sdk}.metallib"
    _run(["xcrun", "--sdk", sdk, "metal", "-c", str(input_metal), "-o", str(air)])
    _run(["xcrun", "--sdk", sdk, "metallib", str(air), "-o", str(lib)])
    return lib.read_bytes()


def _b64_lines(data: bytes, width: int = 76) -> str:
    s = base64.b64encode(data).decode("ascii")
    return "\n".join(textwrap.wrap(s, width))


def main() -> None:
    ap = argparse.ArgumentParser(description="Embed platform-specific .metallib in a Swift source file.")
    ap.add_argument("--input", required=True, type=Path, help="Path to .metal source file")
    ap.add_argument("--output", required=True, type=Path, help="Path to output .swift file")
    ap.add_argument("--type-name", required=True, help="Swift type name to define (e.g. MetalLibrary_Foo)")
    args = ap.parse_args()

    input_metal: Path = args.input
    output_swift: Path = args.output
    type_name: str = args.type_name

    with tempfile.TemporaryDirectory() as td:
        tmpdir = Path(td)
        macos = _compile_metallib(input_metal, "macosx", tmpdir)
        iphoneos = _compile_metallib(input_metal, "iphoneos", tmpdir)
        iphonesim = _compile_metallib(input_metal, "iphonesimulator", tmpdir)

    macos_b64 = _b64_lines(macos)
    iphoneos_b64 = _b64_lines(iphoneos)
    iphonesim_b64 = _b64_lines(iphonesim)

    swift = f"""// Generated by tools/metal/embed_metallib.py; do not edit.
import Foundation

enum {type_name} {{
    static let data: Data = {{
        let b64: String
        #if os(macOS)
        b64 = \"\"\"\n{macos_b64}\n\"\"\"
        #elseif os(iOS) || os(visionOS)
        #if targetEnvironment(simulator)
        b64 = \"\"\"\n{iphonesim_b64}\n\"\"\"
        #else
        b64 = \"\"\"\n{iphoneos_b64}\n\"\"\"
        #endif
        #else
        b64 = \"\"\"\n{macos_b64}\n\"\"\"
        #endif

        guard let d = Data(base64Encoded: b64, options: .ignoreUnknownCharacters) else {{
            preconditionFailure(\"Failed to decode embedded metallib for {type_name}\")
        }}
        return d
    }}()
}}
"""

    output_swift.parent.mkdir(parents=True, exist_ok=True)
    output_swift.write_text(swift, encoding="utf-8")


if __name__ == "__main__":
    main()

